# Site settings
title: Javi Bertos - Javivi - Web Developer
description: "A blog about lorem ipsum ..."
baseurl: "" # for test: remove string '/space-jekyll-template' to ''
url: "https://javibertos.github.io/" # for test: remove string 'http://victorvoid.github.io' to '' but in production: 'https://yourusername.githu.io'

# User settings
username: Ja(r)vi(s) Bertos
user_title: Web Developer - Tech player
email: yo@javierbertos.name
twitter_username: javibertos
github_username:  javibertos
gplus_username:  javibertos
linkedin_public_url: jbertos # Example: For public profile 'www.linkedin.com/in/john-smith', 'john-smith' is your linkedin_public_url
disqus_username: javibertos
profile_picture: https://en.gravatar.com/userimage/2230120/06e8a513a6da6aba3f85b4d4223f24ef.jpg?size=200

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
links:
  section_1:
    - title: home
      url: /
      key_trigger: 1
    - title: my posts
      url: /posts
      key_trigger: 2
    - title: series
      url: /series
      key_trigger: 3
    - title: tags
      url: /tags
      key_trigger: 4
    - title: about me
      url: /about
      key_trigger: 5
  section_2:
    - title: search
      url: ""
      key_trigger: s #WARNING: search only works with "s"
  section_3:
    - title: github
      url: https://www.github.com/javibertos
      new_tab: true
      external: true
    - title: twitter
      url: https://www.twitter.com/javibertos
      external: true

# projects in header index
projects:

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']

theme: jekyll-theme-hacker